server:
  port: 7200
  servlet:
    context-path: /monitor
management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers,metrics,beans,mappings,threaddump,heapdump,swagger-ui,sbom

monitor:
  urls:
    - name: Roach.gy Site
      url: https://roach.gy/ping.txt
    - name: Docops Extension
      url: https://roach.gy/extension/api/ping
    - name: Docops Extension Health
      url: https://roach.gy/extension/actuator/health
  scheduler:
    intervalSeconds: 30
  api:
    url: https://roach.gy/monitor-persistence/api/records
