server:
  port: 7200
  servlet:
    context-path: /monitor
management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers,metrics,beans,mappings,threaddump,heapdump,swagger-ui,sbom

monitor:
  urls:
    - name: Roach Ping
      url: https://roach.gy/ping.txt
    - name: Roach API Ping
      url: https://roach.gy/extension/api/ping
    - name: Roach Health
      url: https://roach.gy/extension/actuator/health
  scheduler:
    intervalSeconds: 30
  api:
    url: http://localhost:7201/monitor-persistence/api/records
